export const LOGGED_IN = 'LOGGED_IN';
export const LOGGING_IN = 'LOGGING_IN';
export const LOGOUT = 'LOGOUT';

export const TOGGLE_SIDER = 'TOGGLE_SIDER';

export const ADD_TO_DROPDOWN = 'ADD_TO_DROPDOWN';
export const REMOVE_FROM_DROPDOWN = 'REMOVE_FROM_DROPDOWN';

export const SET_USER_INFO = 'SET_USER_INFO';
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO';

export const SET_EDITOR_INDICATOR = 'SET_EDITOR_INDICATOR';
export const RESET_EDITOR_INDICATOR = 'RESET_EDITOR_INDICATOR';
