version: '3.8'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 5000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abcd1234
    volumes:
      - ./database/:/data/db/

  mongo-express:
    image: mongo-express:0.54
    restart: unless-stopped
    ports:
      - 7000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: abcd1234
